### ISSUE TITLE
[BUG] Bad performance on xfce

### ISSUE THREAD

**Issue by gnzsnz** [linuxserver/docker-rdesktop#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

bad xrdp performance on xcfe desktop (potentially affecting other flavors)

xfce window manager composition is affecting performance, disabling has a significant improvement on performance, with minor funcionality impact

![image](https://github.com/linuxserver/docker-rdesktop/assets/8376642/65f7c3a1-f70a-4c52-bbfc-19479183a005)

command line

```bash
xfconf-query --channel=xfwm4 --property=/general/use_compositing --type=bool --set=false --create
```

it might be possible to disable composition directly on Xorg

```
Section "Extensions"
 Option "Composite" "Disable"
EndSection
```

although I have not tested it, this could be a good solution for the base image

### Expected Behavior

improved performance

### Steps To Reproduce

Install an app use it daily, performance is lagging

### Environment

```markdown
- OS: ubuntu 22.04
- How docker service was installed: official docker ppa
```

### CPU architecture

x86-64

### Docker creation

```bash
sample docker-compose.yml
```

### Container logs

```bash
nothing is displayed on the logs

Performance is greatly improved after disabling window manager composition


xfconf-query --channel=xfwm4 --property=/general/use_compositing --type=bool --set=false --create
```

**Comment by gnzsnz** [comment]
let me know if i need to add any further detail to avoid this issue been closed

**Comment by thelamer** [comment]
I synced what we do in webtop on init 
https://github.com/linuxserver/docker-rdesktop/blob/master/root/defaults/startwm.sh#L3
It requires the container is restarted one time or an existing home directory is mounted in but it is the best I can do with xfce and not need to babysit it.

**Comment by gnzsnz** [comment]
thanks for your reply @thelamer 

I'm disabling composition like [this](https://github.com/gnzsnz/ib-gateway-docker/blob/a94f3efdc8489058cb9e082ee4879cedf9525f21/latest/tws-scripts/run_tws.sh#L32),         

`xfconf-query --channel=xfwm4 --property=/general/use_compositing --type=bool --set=false --create`

which has the same end result, and less dependencies.

just to highlight another alternative. I'm fine with both options
