### ISSUE TITLE
[FEAT] GPU hw acceleration support for Raspi 5

### ISSUE THREAD

**Issue by markussc** [linuxserver/docker-rdesktop#151]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It seems that even when using the option `--device=/dev/dri:/dev/dri` , the HW acceleration is not available inside the RD session if the host is a Raspi 5 (running Ubuntu 24.04). Also `dtoverlay=vc4-fkms-v3d` is set in the config.txt
Software like firefox or thunderbird show weird graphic artefacts.

### Reason for change

It would be nice if you could add support for Raspi 5 as it is much more powerful than the previous versions and can be used as a real RDP host.

**Comment by thelamer** [comment]
This might be possible using Zink and mesa-vulkan-broadcom for acceleration https://pkgs.alpinelinux.org/package/edge/main/aarch64/mesa-vulkan-broadcom, can you test this out for us? 

If using Alpine try this env var: 

`-e DOCKER_MODS=linuxserver/mods:universal-package-install -e INSTALL_PACKAGES=mesa-vulkan-broadcom`

When you are inside the container launch something like firefox and try a webgl test: 

```
LIBGL_KOPPER_DRI2=1 MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink firefox
```
