### ISSUE TITLE
ssh client in rdesktop image

### ISSUE THREAD

**Issue by MichaelTrip** [linuxserver/docker-rdesktop#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
The possibility to use the `ssh` command in the rdesktop docker container

## Current Behavior
There is no `ssh` command available. 

## Alternatives Considered
I could change the Dockerfile to add the ssh package to it. Should i create a new PR for the new docker file?

**Comment by aptalca** [comment]
No need to mess with dockerfiles
See here about adding a simple custom script to install it on container start: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by thelamer** [comment]
This is in the latest images.
