### ISSUE TITLE
Possibility to add others folder/disks

### ISSUE THREAD

**Issue by Stephen988** [linuxserver/docker-rdesktop#36]
Hello,
there is a way to explore other folder of host system? with the volume: /path/to/data:/config  I can only see the content of this specific folder, is possible mount others folders/disk, for example see content of my host home folder?

**Comment by aptalca** [comment]
You can add any mount you like

**Comment by Stephen988** [comment]
> You can add any mount you like

how? can you write me an example of folder path:"and here what write?"

**Comment by aptalca** [comment]
It's explained in the readme as well as docker docs. Feel free to drop by our discord for further help.

Closing as this is not a bug

**Comment by Stephen988** [comment]
> It's explained in the readme as well as docker docs. Feel free to drop by our discord for further help.
> 
> Closing as this is not a bug

chats of linuxserver discord is always closed 🔐🤷🏻‍♂️

**Comment by aptalca** [comment]
You need to read the rules and the instructions
