### ISSUE TITLE
Firefox in Jammy is not starting

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/docker-rdesktop#41]
Hi;

Firefox doesn't start when I use the Ubuntu-KDE which is based on Jammy.
From what I understand, Jammy rely heavily on snap app, and I think snap inside Docker don't play well.
I created a VM, try to install Firefox via apt install Firefox, and this command will install the snap version;
it seems to be the same issue here

![image](https://user-images.githubusercontent.com/5204724/164131825-08ede266-5652-41d0-9f62-0a74773058bf.png)

What do you think ?

**Comment by thelamer** [comment]
Sorry for the delay I have been MIA for work, I am gonna rebase these all to Jammy and install from the Mozilla PPA like we do in webtops: 
https://github.com/linuxserver/docker-webtop/blob/ubuntu-kde/Dockerfile#L11-L21

**Comment by thelamer** [comment]
This is resolved at head
