### ISSUE TITLE
How to add multilingual support

### ISSUE THREAD

**Issue by laiqinghua** [linuxserver/docker-rdesktop#44]
Cannot display simplified Chinese，How should I solve it。ths

**Comment by laiqinghua** [comment]
如果大家在国中可以使用阿里云镜像源：
 echo "https://mirrors.aliyun.com/alpine/edge/testing/" >> /etc/apk/repositories
apk update
apk add wqy-zenhei

-------------------------
If you also encounter the problem that Firefox text cannot be displayed normally in other countries.

1. Add the alpine / edge / testing source of your country.

2. Use "APK update"

3. Add common fonts in your national language Linux system. For example, China: wqy zenhei

**Comment by coppercash** [comment]
```bash
apt-get install
        ### east asian fonts ###
        # https://en.wikipedia.org/wiki/Help:Multilingual_support_%28East_Asian%29#Debian-based_GNU.2FLinux
        fonts-arphic-ukai \
        fonts-arphic-uming \
        fonts-ipafont-mincho \
        fonts-ipafont-gothic \
        fonts-unfonts-core \
;
```

I found this also works.
