### ISSUE TITLE
GNOME Support

### ISSUE THREAD

**Issue by niwla23** [linuxserver/docker-rdesktop#45]
Would it be possible to add GNOME Support to docker-rdesktop or is there a technical reason why it is not supported?

**Comment by niwla23** [comment]
bump

**Comment by niwla23** [comment]
bump

**Comment by thelamer** [comment]
Yeah gnome needs systemd/dbus and it is nightmare to run in Docker without extreme modifications. 
There are ways of doing it but I am not going to be maintaining it.

**Comment by niwla23** [comment]
That makes sense. I will close this issue then.
