### ISSUE TITLE
Timezone not properly set with environment variable

### ISSUE THREAD

**Issue by MxD-js** [linuxserver/docker-rdesktop#6]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Would expect setting -e TZ=America/Los_Angeles in the run command for docker would set PST time zone

## Current Behavior
Running "date" in the terminal, time zone in UTC. 

## Steps to Reproduce

1. create new container w/ -e TZ=America/Los_Angeles
2. launch terminal in container
3. run "date"
4. verify, timezone not set to PST, set to UTC instead.

## Environment
**OS:**   Ubuntu 20.04   
**CPU architecture:** x86_64     
**How docker service was installed:**      

I used this guide. 
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04

## Command used to create docker container (run/create/compose/screenshot)

`docker run -d \
  --name=rdesktop_demo \
  -e PUID=1000 \
  -e PGID=1000 \
  --privileged `#optional` \
  -e TZ=America/Los_Angeles \
  --net=host \
  -v /home/username/docker-data/rdesktop/data:/config `#optional` \
  --shm-size="1gb" `#optional` \
  --restart unless-stopped \
  linuxserver/rdesktop:mate-focal
`

**Comment by aptalca** [comment]
It works fine here:
```
aptalca@jenkins:~$ docker run -d --rm --name test -e TZ=America/Los_Angeles linuxserver/rdesktop:mate-focal
8f63793b21f0c4350f1f1d8c9c7207e21f0c7b7e6485a0c1e9a01ac9b04b78e1
aptalca@jenkins:~$ docker exec -it test date
Sun 27 Sep 2020 11:46:16 AM PDT
```

**Comment by MxD-js** [comment]
Issue Closed.. I cannot replicate it. Rebooted ubuntu docker host, and now works. Unsure of the real cause.

**Comment by aptalca** [comment]
It seems the system wide setting is correct, but perhaps mate is overriding it with its own settings. Cheech to see if there is a gui option

**Comment by MxD-js** [comment]
This also happens with kde-focal tag. Issue becomes when I lunch gui apps and they are using the wrong timezone. Running 'date' in the terminal returns proper time and timezone  but not sure where the Gui apps get their time.
