### ISSUE TITLE
rdesktop-web Based Image

### ISSUE THREAD

**Issue by alexyao2015** [linuxserver/docker-rdesktop#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
Would we be able to get a similar image except with a base of the lsiobase/rdesktop-web? This would allow for easy usage of desktops through a web browser.
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by thelamer** [comment]
https://hub.docker.com/r/linuxserver/webtop
